server:
  port: 8081
  error:
    include-stacktrace: always
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/recipe?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: db_ADM83!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update