server:
  port: 8081
  error:
    include-stacktrace: always
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/recipe?useSSL=false
    username: root
    password: db_ADM83!
  jpa:
    hibernate:
      ddl-auto: update